Linting and testing TS integration
auth0/auth0-deploy-cli pull request #433
Opened 2022-03-08 20:06 UTC by willvedd

## ✏️ Changes

The initial Typescript tooling PR (#426) only covered the build step. However, it was soon discovered that our linting and unit testing processes are incompatible with Typescript. For that reason, had to make a number of small changes (highlighted below) to ensure that all our scripts function as expected for both `.js` and `.ts` file extensions.

One benefit here is that we were able to completely remove Babel as a dependency and instead rely almost completely on Typescript and thing TS wrappers.

## 🎯 Testing

No unit tests necessary as this just _runs_ the unit tests.

2022-03-08 20:09 UTC, willvedd commented on tsconfig.json
> -    /* Visit https://aka.ms/tsconfig.json to read more about this file */
Comments are not valid JSON and as such caused the `ts-mocha` dependency to choke.

2022-03-08 20:10 UTC, willvedd commented on package.json
> +    "test": "ts-mocha -p tsconfig.json --recursive 'test/**/*.test.*'",
From what I could tell, the `cross-env` and `nyc` dependencies weren't providing any meaningful functionality. My observations seemed to indicate that these two were functionally identical.

2022-03-08 20:11 UTC, willvedd commented on .eslintrc
> +      }
This is to quell eslint warnings about being unable to resolve modules.

2022-03-09 08:39 UTC, sergiughf requested changes

2022-03-09 08:39 UTC, sergiughf commented on .eslintrc
> +}
Missing new line. 🙃

2022-03-09 08:39 UTC, sergiughf commented on tsconfig.json
> +}
Missing new line. 🙃

2022-03-09 17:08 UTC, merged